---
- name: Import PostgreSQL repository signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Create PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present

- name: Install PostgreSQL latest stable version ({{ postgresql_version }})
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}

- name: Install psycopg2 Python module
  ansible.builtin.apt:
    name:
      - libpq-dev
      - python3-psycopg2
    state: present
