---
- name: Install Podman and corresponding Python module
  ansible.builtin.dnf:
    name:
      - podman
      - python-podman-api
    state: present

- name: Ensure Podman is enabled and started
  ansible.builtin.systemd:
    name: podman
    enabled: true
    state: started

- name: Start nginx Docker container
  containers.podman.podman_container:
    name: '{{ ansible_hostname }}'
    image: library/nginx:stable-alpine
    volume:
      - /opt/nginx.conf:/etc/nginx/conf.d/default.conf
    publish:
      - 80:80
    restart: true
    state: started
