---
- name: Processing CentOS host(s)...
  include: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Processing Ubuntu host(s)...
  include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
