---
- name: Add system users
  ansible.builtin.user:
    name: '{{ item.user }}'
    shell: /bin/bash
    state: present
  with_items: '{{ base_users_add }}'

- name: Set system users' authorized keys
  ansible.builtin.authorized_key:
    user: '{{ item.user }}'
    key: '{{ item.key }}'
    state: present
  with_items: '{{ base_users_add }}'

- name: Create nginx config
  ansible.builtin.copy:
    dest: /opt/nginx.conf
    content: |
      server {
        listen 80 default_server;
        server_name _;
        return 444;
      }

      server {
        server_name {{ datacenter }}-{{ ansible_hostname }};
        add_header Content-Type text/plain;
        return 200 'Hello \n';
      }
